#!/usr/bin/env python3

import logging
import argparse

from calabo import CalaboServer



LOG = logging.getLogger("calabo_server")



def main():
    LOG.addHandler(logging.StreamHandler())

    parser = argparse.ArgumentParser(description="calabo_server.")
    parser.add_argument(
        "--verbose", "-v",
        action="count", default=0,
        help="Print verbose information for debugging.")
    parser.add_argument(
        "--quiet", "-q",
        action="count", default=0,
        help="Suppress warnings.")

    parser.add_argument(
        "device",
        metavar="DEVICE",
        help="Address of serial device.")

    args = parser.parse_args()

    level = (logging.ERROR, logging.WARNING, logging.INFO, logging.DEBUG)[
        max(0, min(3, 1 + args.verbose - args.quiet))]
    LOG.setLevel(level)

    with CalaboServer(args.device) as calabo_server:
        calabo_server.run()



if __name__ == "__main__":
    main()
